
spring:
  application:
    name: config-client

  cloud:
    config:
      label: master
      profile: dev
      discovery:
        enabled: true
        serviceId: config-client
  #      uri: http://localhost:8888/


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8881