
spring:
  application:
    name: config-client

  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/
      username: vothin
      password: Zero.1995


server:
  port: 8881