eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8765

spring:
  application:
    name: feign-server

feign:
  hystrix:
    enabled: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
