
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/vothin/config-eureka-client-demo
          searchPaths: config-eureka-client-demo
          username: vothin
          password: Zero.1995


server:
  port: 8888


