
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/vothin/SpringCloudConfigDemo/
          searchPaths: config
#          username: vothin
#          password: Zero.1995
#          uri: https://github.com/forezp/SpringcloudConfig/
#          searchPaths: respo


server:
  port: 8888


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
